FROM

# Set the JBOSS_HOME env variable
ENV JBOSS_HOME /opt/jboss/wildfly-8.2.1.Final

# Expose the ports we're interested in 
EXPOSE 8080 9990



CMD ["/opt/jboss/wildfly-8.2.1.Final/bin/standalone.sh", "-b", "0.0.0.0"]
